-- ============================================
-- Season Opt-In and Player Approval System
-- Run this in Supabase SQL Editor
-- ============================================

-- Create enum for opt-in types
DO $$ BEGIN
  CREATE TYPE opt_in_type AS ENUM ('full_time', 'call_up');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create enum for approval methods
DO $$ BEGIN
  CREATE TYPE approval_method AS ENUM ('owner', 'invite', 'auto');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- ============================================
-- SEASON OPT-INS
-- Players must opt in before each season
-- ============================================

CREATE TABLE IF NOT EXISTS season_opt_ins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  player_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  season_id UUID NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  opt_in_type opt_in_type NOT NULL DEFAULT 'full_time',
  opted_in_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(player_id, season_id) -- One opt-in per player per season
);

CREATE INDEX IF NOT EXISTS idx_season_opt_ins_season ON season_opt_ins(season_id);
CREATE INDEX IF NOT EXISTS idx_season_opt_ins_player ON season_opt_ins(player_id);
CREATE INDEX IF NOT EXISTS idx_season_opt_ins_type ON season_opt_ins(season_id, opt_in_type);

COMMENT ON TABLE season_opt_ins IS 'Player opt-ins for each season (full-time or call-up)';
COMMENT ON COLUMN season_opt_ins.opt_in_type IS 'full_time: can be drafted as regular player, call_up: only available as substitute/emergency';

-- ============================================
-- PLAYER APPROVALS
-- Track how players were approved to join the league
-- ============================================

CREATE TABLE IF NOT EXISTS player_approvals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  player_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  approved_by UUID REFERENCES profiles(id) ON DELETE SET NULL, -- Owner who approved, or NULL if auto-approved
  approved_at TIMESTAMPTZ DEFAULT NOW(),
  approval_method approval_method NOT NULL DEFAULT 'owner',
  invite_code_id UUID, -- If approved via invite, link to the invite code
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_player_approvals_player ON player_approvals(player_id);
CREATE INDEX IF NOT EXISTS idx_player_approvals_method ON player_approvals(approval_method);

COMMENT ON TABLE player_approvals IS 'Tracks how players were approved to join the league';
COMMENT ON COLUMN player_approvals.approval_method IS 'owner: manually approved by owner, invite: auto-approved via invite code, auto: system auto-approved';

-- ============================================
-- INVITE CODES
-- Captains can generate invite codes for call-ups/guests
-- ============================================

CREATE TABLE IF NOT EXISTS invite_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT NOT NULL UNIQUE, -- Unique invite code
  created_by UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, -- Captain who created it
  team_id UUID REFERENCES teams(id) ON DELETE SET NULL, -- Optional: specific team invite
  season_id UUID REFERENCES seasons(id) ON DELETE SET NULL, -- Optional: for specific season
  expires_at TIMESTAMPTZ, -- Optional expiration
  max_uses INTEGER DEFAULT 1, -- How many times it can be used
  current_uses INTEGER DEFAULT 0, -- How many times it's been used
  used_by UUID REFERENCES profiles(id) ON DELETE SET NULL, -- Who used it (if single use)
  used_at TIMESTAMPTZ, -- When it was used
  auto_approve BOOLEAN DEFAULT TRUE, -- Auto-approve players who use this code
  notes TEXT, -- Optional notes about the invite
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_created_by ON invite_codes(created_by);
CREATE INDEX IF NOT EXISTS idx_invite_codes_team ON invite_codes(team_id);
CREATE INDEX IF NOT EXISTS idx_invite_codes_season ON invite_codes(season_id);

COMMENT ON TABLE invite_codes IS 'Invite codes generated by captains for call-ups/guests';
COMMENT ON COLUMN invite_codes.auto_approve IS 'If true, players using this code are automatically approved';

-- ============================================
-- FUNCTIONS
-- ============================================

-- Function to generate a unique invite code
CREATE OR REPLACE FUNCTION generate_invite_code()
RETURNS TEXT AS $$
DECLARE
  code TEXT;
  exists_check BOOLEAN;
BEGIN
  LOOP
    -- Generate a random 8-character alphanumeric code
    code := UPPER(
      SUBSTRING(
        MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT),
        1, 8
      )
    );
    
    -- Check if code already exists
    SELECT EXISTS(SELECT 1 FROM invite_codes WHERE invite_codes.code = code) INTO exists_check;
    
    -- Exit loop if code is unique
    EXIT WHEN NOT exists_check;
  END LOOP;
  
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- Function to check if invite code is valid
CREATE OR REPLACE FUNCTION is_invite_code_valid(code_to_check TEXT)
RETURNS TABLE(
  is_valid BOOLEAN,
  invite_id UUID,
  team_id UUID,
  season_id UUID,
  auto_approve BOOLEAN
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    CASE 
      WHEN ic.id IS NULL THEN FALSE
      WHEN ic.expires_at IS NOT NULL AND ic.expires_at < NOW() THEN FALSE
      WHEN ic.current_uses >= ic.max_uses THEN FALSE
      ELSE TRUE
    END as is_valid,
    ic.id as invite_id,
    ic.team_id,
    ic.season_id,
    ic.auto_approve
  FROM invite_codes ic
  WHERE ic.code = code_to_check
  LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Function to use an invite code
CREATE OR REPLACE FUNCTION use_invite_code(
  code_to_use TEXT,
  user_id UUID
)
RETURNS TABLE(
  success BOOLEAN,
  message TEXT,
  invite_id UUID
) AS $$
DECLARE
  invite_record RECORD;
  validation_result RECORD;
BEGIN
  -- Check if code is valid
  SELECT * INTO validation_result
  FROM is_invite_code_valid(code_to_use);
  
  IF NOT validation_result.is_valid THEN
    RETURN QUERY SELECT FALSE, 'Invalid or expired invite code'::TEXT, NULL::UUID;
    RETURN;
  END IF;
  
  -- Get invite details
  SELECT * INTO invite_record
  FROM invite_codes
  WHERE code = code_to_use;
  
  -- Update invite code usage
  UPDATE invite_codes
  SET 
    current_uses = current_uses + 1,
    used_by = CASE WHEN max_uses = 1 THEN user_id ELSE used_by END,
    used_at = CASE WHEN max_uses = 1 THEN NOW() ELSE used_at END,
    updated_at = NOW()
  WHERE id = invite_record.id;
  
  -- Auto-approve if enabled
  IF invite_record.auto_approve THEN
    INSERT INTO player_approvals (player_id, approval_method, invite_code_id)
    VALUES (user_id, 'invite', invite_record.id)
    ON CONFLICT DO NOTHING; -- Don't duplicate if already approved
  END IF;
  
  RETURN QUERY SELECT TRUE, 'Invite code used successfully'::TEXT, invite_record.id;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- RLS POLICIES
-- ============================================

ALTER TABLE season_opt_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;

-- Season Opt-Ins: Players can view all, manage their own
CREATE POLICY "Season opt-ins are viewable by everyone" ON season_opt_ins
  FOR SELECT USING (true);

CREATE POLICY "Players can manage own opt-ins" ON season_opt_ins
  FOR ALL USING (auth.uid() = player_id);

CREATE POLICY "Owners can manage all opt-ins" ON season_opt_ins
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

-- Player Approvals: Viewable by all, manageable by owners
CREATE POLICY "Player approvals are viewable by everyone" ON player_approvals
  FOR SELECT USING (true);

CREATE POLICY "Only owners can manage approvals" ON player_approvals
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

-- Invite Codes: Viewable by creator and owners, manageable by creators and owners
CREATE POLICY "Invite codes viewable by creator and owners" ON invite_codes
  FOR SELECT USING (
    created_by = auth.uid()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

CREATE POLICY "Captains and owners can create invite codes" ON invite_codes
  FOR INSERT WITH CHECK (
    created_by = auth.uid()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

CREATE POLICY "Captains and owners can update own invite codes" ON invite_codes
  FOR UPDATE USING (
    created_by = auth.uid()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

-- ============================================
-- VERIFY CREATION
-- ============================================

SELECT 
  'season_opt_ins' as table_name,
  column_name,
  data_type
FROM information_schema.columns
WHERE table_name = 'season_opt_ins'
UNION ALL
SELECT 
  'player_approvals' as table_name,
  column_name,
  data_type
FROM information_schema.columns
WHERE table_name = 'player_approvals'
UNION ALL
SELECT 
  'invite_codes' as table_name,
  column_name,
  data_type
FROM information_schema.columns
WHERE table_name = 'invite_codes'
ORDER BY table_name, column_name;
