-- ============================================================================
-- Migration: merge-completeness fix for the two profile-merge RPCs.
--
-- Both merge_legacy_profile() and claim_rostered_player_profile() reassign a
-- source (legacy/stub) profile's rows to the surviving profile and then DELETE
-- the source. Any player-referencing table they forgot to reassign is therefore
-- CASCADE-deleted or SET NULL when that DELETE runs. This migration brings both
-- RPCs to parity and closes the confirmed gaps:
--   * player_career_baselines.player_id  (paid imported career totals — SET NULL)
--   * captain_player_invites.target_player_id (invite audit row — CASCADE)
--   * league_spare_pool.player_id        (spare-pool membership — CASCADE, unique)
--   * sub_invitations.replaced_player_id (replacement attribution — SET NULL)
--   * teams.captain_id + player_goalie_matchups.goalie_id (merge_legacy_profile
--       was missing these; claim_rostered_player_profile already had them)
--   * goalie_requests.requested_by / goalie_ratings.rated_by /
--       draft_roster_confirmations.confirmed_by (NOT NULL actor FKs — reassigned
--       so an imported/backfilled stub cannot block the DELETE and silently abort)
--
-- Intentionally NOT reassigned (documented, low risk):
--   * player_rating_contexts — derived from the reassigned stat tables; it is
--       regenerated by the rating engine on the next recompute.
--   * scorekeeper_availability — can only be written by an authenticated user
--       (RLS: scorekeeper_id = auth.uid()), so a source stub (no auth.users row)
--       can never hold rows here; nothing to reassign.
--
-- ⚠️  UNTESTED IN CI: authored by static analysis; the project's migrations do not
--     replay cleanly on a throwaway DB. VALIDATE ON STAGING before production
--     (apply, run a real merge, and confirm the previously-missing tables carry
--     over). See the verification query at the bottom of this file.
--
-- Both function bodies below are the current definitions verbatim, with only the
-- new reassignment block inserted immediately before their "UPDATE profiles SET
-- ... legacy_merge_completed_at" finalization step.
-- ============================================================================

BEGIN;

CREATE OR REPLACE FUNCTION public.merge_legacy_profile(
  p_new_profile_id UUID,
  p_legacy_profile_id UUID
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_reassigned INTEGER := 0;
  v_count INTEGER;
  v_legacy_player_id UUID;
  v_legacy_avatar_url TEXT;
  v_legacy_photo_url TEXT;
BEGIN
  SELECT legacy_player_id, avatar_url, photo_url
  INTO v_legacy_player_id, v_legacy_avatar_url, v_legacy_photo_url
  FROM profiles
  WHERE id = p_legacy_profile_id
    AND is_legacy_import = TRUE
    AND legacy_merge_completed_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Legacy profile % not found or already merged', p_legacy_profile_id;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM profiles
    WHERE id = p_new_profile_id
      AND (is_legacy_import IS NULL OR is_legacy_import = FALSE)
  ) THEN
    RAISE EXCEPTION 'Target profile % not found or is itself a legacy profile', p_new_profile_id;
  END IF;

  UPDATE team_rosters SET player_id = p_new_profile_id
  WHERE player_id = p_legacy_profile_id
    AND NOT EXISTS (
      SELECT 1 FROM team_rosters tr2
      WHERE tr2.player_id = p_new_profile_id
        AND tr2.team_id = team_rosters.team_id
        AND tr2.season_id = team_rosters.season_id
        AND tr2.end_date IS NULL
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;
  DELETE FROM team_rosters WHERE player_id = p_legacy_profile_id;

  UPDATE player_stats SET player_id = p_new_profile_id
  WHERE player_id = p_legacy_profile_id
    AND NOT EXISTS (
      SELECT 1 FROM player_stats ps2
      WHERE ps2.player_id = p_new_profile_id
        AND ps2.season_id = player_stats.season_id
        AND ps2.team_id = player_stats.team_id
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;
  DELETE FROM player_stats WHERE player_id = p_legacy_profile_id;

  UPDATE game_stats SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE goalie_stats SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_events SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_events SET assist1_player_id = p_new_profile_id WHERE assist1_player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_events SET assist2_player_id = p_new_profile_id WHERE assist2_player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_checkins SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_duties SET assigned_player_id = p_new_profile_id WHERE assigned_player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE game_stat_entry_log SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE league_awards SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE suspensions SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_payments SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE payments SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_approvals SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_availability SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_badges SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_goalie_matchups SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_ratings SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE player_waivers SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE registration_submissions SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE season_opt_ins SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE sub_invitations SET invited_player_id = p_new_profile_id WHERE invited_player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE team_join_requests SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE trade_players SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE draft_picks SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE draft_pool SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE article_player_tags SET player_id = p_new_profile_id WHERE player_id = p_legacy_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;


  -- ============================================================================
  -- Merge-completeness fix (2026-07-03): reassign player-referencing rows that
  -- were previously CASCADE-deleted / SET NULL when the source profile is deleted.
  -- ============================================================================
  v_count := public._claim_update_uuid_column_if_exists('teams', 'captain_id', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('player_goalie_matchups', 'goalie_id', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('captain_player_invites', 'target_player_id', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('player_career_baselines', 'player_id', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('sub_invitations', 'replaced_player_id', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('goalie_requests', 'requested_by', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('goalie_ratings', 'rated_by', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('draft_roster_confirmations', 'confirmed_by', p_new_profile_id, p_legacy_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  -- league_spare_pool has UNIQUE(league_id, player_id): reassign non-colliding rows, drop leftover duplicates.
  IF to_regclass('public.league_spare_pool') IS NOT NULL THEN
    UPDATE league_spare_pool SET player_id = p_new_profile_id
    WHERE player_id = p_legacy_profile_id
      AND NOT EXISTS (
        SELECT 1 FROM league_spare_pool lsp2
        WHERE lsp2.player_id = p_new_profile_id
          AND lsp2.league_id = league_spare_pool.league_id
      );
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_total_reassigned := v_total_reassigned + v_count;
    DELETE FROM league_spare_pool WHERE player_id = p_legacy_profile_id;
  END IF;

  UPDATE profiles SET
    legacy_player_id = v_legacy_player_id,
    avatar_url = COALESCE(NULLIF(avatar_url, ''), NULLIF(v_legacy_avatar_url, ''), NULLIF(v_legacy_photo_url, '')),
    photo_url = COALESCE(NULLIF(photo_url, ''), NULLIF(v_legacy_photo_url, ''), NULLIF(v_legacy_avatar_url, '')),
    legacy_merge_completed_at = NOW(),
    pending_legacy_match_ids = '{}',
    updated_at = NOW()
  WHERE id = p_new_profile_id;

  UPDATE legacy_players
  SET matched_to_profile_id = p_new_profile_id,
      matched_at = NOW(),
      updated_at = NOW()
  WHERE matched_to_profile_id = p_legacy_profile_id;

  DELETE FROM profiles WHERE id = p_legacy_profile_id;

  RETURN jsonb_build_object(
    'success', true,
    'total_reassigned', v_total_reassigned,
    'legacy_profile_deleted', p_legacy_profile_id,
    'merged_into', p_new_profile_id
  );
EXCEPTION
  WHEN others THEN
    RAISE WARNING 'merge_legacy_profile failed: %', SQLERRM;
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_rostered_player_profile(
  p_target_profile_id UUID,
  p_claim_profile_id UUID
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_reassigned INTEGER := 0;
  v_count INTEGER;
  v_claim_profile RECORD;
  v_target_profile RECORD;
BEGIN
  IF p_target_profile_id IS NULL OR p_claim_profile_id IS NULL THEN
    RAISE EXCEPTION 'Both target and claim profile IDs are required';
  END IF;

  IF p_target_profile_id = p_claim_profile_id THEN
    RAISE EXCEPTION 'Cannot claim a profile into itself';
  END IF;

  SELECT id, email, full_name, is_legacy_import, legacy_player_id
  INTO v_target_profile
  FROM profiles
  WHERE id = p_target_profile_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Target profile % not found', p_target_profile_id;
  END IF;

  IF COALESCE(v_target_profile.is_legacy_import, FALSE) = TRUE THEN
    RAISE EXCEPTION 'Target profile % is a legacy import and cannot claim another player', p_target_profile_id;
  END IF;

  SELECT id, email, full_name, phone, position, jersey_number, is_legacy_import, legacy_player_id, legacy_merge_completed_at
  INTO v_claim_profile
  FROM profiles
  WHERE id = p_claim_profile_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Claim profile % not found', p_claim_profile_id;
  END IF;

  -- Hard safety guard: never allow claiming a profile that already has an auth user.
  -- This covers current real accounts; unclaimed imported/current player stubs have no auth.users row.
  IF EXISTS (SELECT 1 FROM auth.users au WHERE au.id = p_claim_profile_id) THEN
    RAISE EXCEPTION 'Claim profile % is already attached to a user account', p_claim_profile_id;
  END IF;

  -- Hard safety guard: only rostered player profiles are claimable.
  IF NOT EXISTS (SELECT 1 FROM team_rosters tr WHERE tr.player_id = p_claim_profile_id) THEN
    RAISE EXCEPTION 'Claim profile % is not rostered and cannot be claimed', p_claim_profile_id;
  END IF;

  IF v_claim_profile.legacy_merge_completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Claim profile % has already been merged', p_claim_profile_id;
  END IF;

  UPDATE teams SET captain_id = p_target_profile_id
  WHERE captain_id = p_claim_profile_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;

  UPDATE team_rosters SET player_id = p_target_profile_id
  WHERE player_id = p_claim_profile_id
    AND NOT EXISTS (
      SELECT 1 FROM team_rosters tr2
      WHERE tr2.player_id = p_target_profile_id
        AND tr2.team_id = team_rosters.team_id
        AND tr2.season_id = team_rosters.season_id
        AND COALESCE(tr2.end_date, DATE '9999-12-31') = COALESCE(team_rosters.end_date, DATE '9999-12-31')
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;
  DELETE FROM team_rosters WHERE player_id = p_claim_profile_id;

  UPDATE player_stats SET player_id = p_target_profile_id
  WHERE player_id = p_claim_profile_id
    AND NOT EXISTS (
      SELECT 1 FROM player_stats ps2
      WHERE ps2.player_id = p_target_profile_id
        AND ps2.game_id = player_stats.game_id
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  v_total_reassigned := v_total_reassigned + v_count;
  DELETE FROM player_stats WHERE player_id = p_claim_profile_id;

  v_count := public._claim_update_uuid_column_if_exists('game_stats', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('goalie_stats', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_events', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_events', 'assist1_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_events', 'assist2_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_checkins', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_duties', 'assigned_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('game_stat_entry_log', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('league_awards', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('suspensions', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_payments', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('payments', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_approvals', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_availability', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_badges', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_goalie_matchups', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_goalie_matchups', 'goalie_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_ratings', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('player_waivers', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('registration_submissions', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('season_opt_ins', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('sub_invitations', 'invited_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('team_join_requests', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('trade_players', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('draft_picks', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('draft_pool', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;

  v_count := public._claim_update_uuid_column_if_exists('article_player_tags', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;


  -- ============================================================================
  -- Merge-completeness fix (2026-07-03): reassign player-referencing rows that
  -- were previously CASCADE-deleted / SET NULL when the source profile is deleted.
  -- ============================================================================
  v_count := public._claim_update_uuid_column_if_exists('captain_player_invites', 'target_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('player_career_baselines', 'player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('sub_invitations', 'replaced_player_id', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('goalie_requests', 'requested_by', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('goalie_ratings', 'rated_by', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  v_count := public._claim_update_uuid_column_if_exists('draft_roster_confirmations', 'confirmed_by', p_target_profile_id, p_claim_profile_id);
  v_total_reassigned := v_total_reassigned + v_count;
  -- league_spare_pool has UNIQUE(league_id, player_id): reassign non-colliding rows, drop leftover duplicates.
  IF to_regclass('public.league_spare_pool') IS NOT NULL THEN
    UPDATE league_spare_pool SET player_id = p_target_profile_id
    WHERE player_id = p_claim_profile_id
      AND NOT EXISTS (
        SELECT 1 FROM league_spare_pool lsp2
        WHERE lsp2.player_id = p_target_profile_id
          AND lsp2.league_id = league_spare_pool.league_id
      );
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_total_reassigned := v_total_reassigned + v_count;
    DELETE FROM league_spare_pool WHERE player_id = p_claim_profile_id;
  END IF;

  UPDATE profiles SET
    full_name = COALESCE(NULLIF(trim(profiles.full_name), ''), v_claim_profile.full_name),
    phone = COALESCE(profiles.phone, v_claim_profile.phone),
    position = COALESCE(profiles.position, v_claim_profile.position),
    jersey_number = COALESCE(profiles.jersey_number, v_claim_profile.jersey_number),
    legacy_player_id = COALESCE(profiles.legacy_player_id, v_claim_profile.legacy_player_id),
    legacy_merge_completed_at = NOW(),
    pending_legacy_match_ids = '{}',
    updated_at = NOW()
  WHERE id = p_target_profile_id;

  UPDATE legacy_players
  SET matched_to_profile_id = p_target_profile_id,
      matched_at = NOW(),
      updated_at = NOW()
  WHERE matched_to_profile_id = p_claim_profile_id
     OR id = v_claim_profile.legacy_player_id;

  DELETE FROM profiles WHERE id = p_claim_profile_id;

  RETURN jsonb_build_object(
    'success', true,
    'total_reassigned', v_total_reassigned,
    'claimed_profile_deleted', p_claim_profile_id,
    'merged_into', p_target_profile_id
  );
EXCEPTION
  WHEN others THEN
    RAISE WARNING 'claim_rostered_player_profile failed: %', SQLERRM;
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;
COMMIT;

-- ============================================================================
-- READ-ONLY verification (run manually on staging AFTER applying):
-- Lists every column that REFERENCES profiles(id) and is NOT handled by either
-- RPC's reassignment. Player-identity columns appearing here would be new gaps.
-- (Actor/audit columns like created_by/updated_by are intentionally left to their
--  SET NULL default; they cannot point at an unclaimed stub in normal operation.)
--
--   SELECT c.conrelid::regclass AS table_name, a.attname AS column_name,
--          c.confdeltype AS on_delete   -- 'c'=cascade, 'n'=set null, 'a'=no action
--   FROM pg_constraint c
--   JOIN unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
--   JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
--   WHERE c.contype = 'f'
--     AND c.confrelid = 'public.profiles'::regclass
--   ORDER BY 1, 2;
-- ============================================================================
